### Sign up
POST http://localhost:3000/api/auth/sign-up
content-type: application/json

{
  "email": "roko4@example.com",
  "password": "somepassword"
}

### Sign in
POST http://localhost:3000/api/auth/sign-in
content-type: application/json

{
  "email": "roko3@example.com",
  "password": "somepassword"
}

### Refresh
POST http://localhost:3000/api/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxOTY3NTA4NSwiZXhwIjoxNzIwMjc5ODg1fQ.6SlsZMBIX25HwBDWuNWWGg5mzP2fM5VB8bQ3EGFvFTE


