### Sign up
POST http://localhost:3000/api/auth/sign-up
content-type: application/json

{
  "email": "roko@example.com",
  "password": "somepassword"
}

### Sign in
POST http://localhost:3000/api/auth/sign-in
content-type: application/json

{
  "email": "roko@example.com",
  "password": "somepassword"
}
